[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  SECRETS_SCAN_ENABLED = "false"
  SECRETS_SCAN_OMIT_KEYS = "VITE_API_URL,MONGODB_DB_NAME,MONGODB_URI"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
