[build]
  publish = "dist"
  command = "npm run build"
  functions = "netlify/functions"

[build.environment]
  SECRETS_SCAN_ENABLED = "false"
  SECRETS_SCAN_OMIT_KEYS = "VITE_API_URL,MONGODB_DB_NAME,MONGODB_URI"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["lightningcss", "vite", "@google/genai", "mongoose", "bcryptjs", "node-domexception"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
